# Concordance — Install all auto-start services (run as Administrator after setup.ps1)
#
# This script:
#   1. Installs cloudflared as a Windows Service using the pre-registered tunnel token
#   2. Registers the API server (uvicorn) as a Task Scheduler task that starts on boot
#   3. Registers an hourly ledger backup task
#
# The Cloudflare tunnel "concordance" was created on 2026-04-30.
# Token authorises the tunnel — keep it private.

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path $PSScriptRoot -Parent
$PythonPath = (Get-Command python).Source
$LogDir     = "C:\Concordance\logs"

# ── Tunnel token (do NOT commit a separate copy of this anywhere public) ────
$TunnelToken = "eyJhIjoiODc4NDllMzg0OWMxZGE2YmNmMWE3MGRiM2EwMjAzMTIiLCJ0IjoiNjM1NDRiMmYtYjE0Ni00MDUzLTk5ZGYtM2UxNTNhNDY5MzQ5IiwicyI6Ik5UQTVaREkxT0RFdE9UaGxZUzAwTkRsbUxXRXpOMkl0WVRrM05ESXdZak0wT0RabSJ9"
$Cloudflared = "C:\Concordance\cloudflared.exe"

Write-Host "`n=== Installing Concordance Services ===" -ForegroundColor Cyan

# ── 1. Cloudflare Tunnel (Windows Service) ──────────────────────────────────
Write-Host "`n[1/3] Installing Cloudflare Tunnel service..." -ForegroundColor Yellow
& $Cloudflared service install $TunnelToken
if ($LASTEXITCODE -ne 0) {
    Write-Error "cloudflared service install failed (exit $LASTEXITCODE)."
}
Start-Service -Name "Cloudflared"
Write-Host "  Service 'Cloudflared' installed and started" -ForegroundColor Green
Write-Host "  Tunnel: concordance  →  narrowhighway.com" -ForegroundColor Green

# ── 2. API Server (Task Scheduler, starts on boot) ─────────────────────────
Write-Host "`n[2/3] Registering API server task..." -ForegroundColor Yellow

# Write a launcher script that sets env vars then starts uvicorn
$ApiLauncher = @"
# Auto-generated by install_services.ps1 — do not edit manually
`$env:LEDGER_PATH                = 'C:\Concordance\data\ledger.jsonl'
`$env:CONCORDANCE_SCHEMA_PATH    = '$RepoRoot\schema\packet.schema.json'
`$env:API_KEY                    = 'lh_786b9711d66ebd502ebe1d4e6b9df64a428edbaad26d81c4'
`$env:PORT                       = '8000'
Set-Location '$RepoRoot'
& '$PythonPath' -m uvicorn api.app:app --host 0.0.0.0 --port 8000 --workers 1 2>&1 |
    Tee-Object -FilePath '$LogDir\server.log' -Append
"@
Set-Content -Path "C:\Concordance\start_server.ps1" -Value $ApiLauncher

$Action    = New-ScheduledTaskAction `
                 -Execute "powershell.exe" `
                 -Argument "-NonInteractive -WindowStyle Hidden -File C:\Concordance\start_server.ps1"
$Trigger   = New-ScheduledTaskTrigger -AtStartup
$Settings  = New-ScheduledTaskSettingsSet `
                 -RestartCount 10 `
                 -RestartInterval (New-TimeSpan -Minutes 1) `
                 -ExecutionTimeLimit (New-TimeSpan -Hours 0)
$Principal = New-ScheduledTaskPrincipal `
                 -UserId "SYSTEM" `
                 -LogonType ServiceAccount `
                 -RunLevel Highest

Register-ScheduledTask -TaskName "Concordance-API" `
    -Action $Action -Trigger $Trigger -Settings $Settings -Principal $Principal -Force |
    Out-Null
Write-Host "  Task 'Concordance-API' registered (runs as SYSTEM, restarts on crash)" -ForegroundColor Green
Start-ScheduledTask -TaskName "Concordance-API"
Start-Sleep -Seconds 3
Write-Host "  Started — health: $(try { (Invoke-RestMethod http://localhost:8000/health).status } catch { 'starting...' })" -ForegroundColor Green

# ── 3. Ledger Backup (hourly) ───────────────────────────────────────────────
Write-Host "`n[3/3] Registering ledger backup task..." -ForegroundColor Yellow

$BackupAction   = New-ScheduledTaskAction `
                      -Execute "powershell.exe" `
                      -Argument "-NonInteractive -WindowStyle Hidden -File '$RepoRoot\local\backup_ledger.ps1'"
$BackupTrigger  = New-ScheduledTaskTrigger -RepetitionInterval (New-TimeSpan -Hours 1) `
                      -Once -At (Get-Date)
$BackupSettings = New-ScheduledTaskSettingsSet

Register-ScheduledTask -TaskName "Concordance-LedgerBackup" `
    -Action $BackupAction -Trigger $BackupTrigger -Settings $BackupSettings -Principal $Principal -Force |
    Out-Null
Write-Host "  Task 'Concordance-LedgerBackup' registered (runs every hour)" -ForegroundColor Green

# ── Done ─────────────────────────────────────────────────────────────────────
Write-Host "`n=== All services installed ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Status commands:" -ForegroundColor White
Write-Host "  Get-Service Cloudflared" -ForegroundColor DarkGray
Write-Host "  Get-ScheduledTask Concordance-API" -ForegroundColor DarkGray
Write-Host "  Invoke-RestMethod http://localhost:8000/health" -ForegroundColor DarkGray
Write-Host ""
Write-Host "Logs:" -ForegroundColor White
Write-Host "  C:\Concordance\logs\server.log" -ForegroundColor DarkGray
Write-Host "  Get-EventLog -LogName Application -Source cloudflared -Newest 20" -ForegroundColor DarkGray
Write-Host ""
Write-Host "IMPORTANT: finish the route in Cloudflare dashboard if not already done." -ForegroundColor Yellow
Write-Host "  dash.cloudflare.com → Zero Trust → Networks → Connectors → concordance" -ForegroundColor DarkGray
Write-Host "  Public Hostnames → Add: narrowhighway.com → HTTP → localhost:8000" -ForegroundColor DarkGray
