# Training Data Schema for Computer Science
# Defines the structure and metadata for computer science training files

schema_version: 1.0
data_types:
  - code_samples
  - algorithm_implementations
  - benchmark_datasets
  - performance_metrics
  - training_datasets

file_formats:
  - csv
  - json
  - py
  - js
  - txt
  - parquet

metadata_required:
  - dataset_name
  - author
  - creation_date
  - description
  - source
  - license
  - version

provenance:
  required: true
  fields:
    - data_source
    - collection_method
    - validation_status
    - last_updated
