#!/usr/bin/env python3
"""build_method_corpus.py — SOVEREIGN method/receipt training pairs.

The card miner (export_corpus.py --cards) teaches attributed RECALL. This teaches
the thing that makes the project unique: deterministic VERIFICATION — given a
claim, produce the worked elimination trail + verdict, and CATCH falsehood. Every
pair is generated by running the LOCAL deterministic engine (api.derivation), so
it is fully sovereign (no cloud, no cost) and never laundered: each completion is
a REAL computed verification, including the ones the engine rightly breaks.

Output: data/training_corpus/corpus-method-<stamp>.jsonl (training_pair/1 schema),
read by the same fine-tune pipeline as the card + gated pairs.

Run: python tools/build_method_corpus.py
"""
from __future__ import annotations
import json
import os
import random
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, ".")
import api.derivation as D  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "data" / "training_corpus"
random.seed(1117)


def eq(a, b):
    return {"mode": "equality", "params": {"expr_a": a, "expr_b": b, "variables": {}}}


def iq(l, r, op):
    return {"mode": "inequality", "params": {"lhs": l, "rhs": r, "op": op, "variables": {}}}


def dv(f, v, d):
    return {"mode": "derivative", "params": {"function": f, "variable": v, "claimed_derivative": d}}


def cases():
    """Yield (prompt, spec) — a balanced spread of true and caught-false claims."""
    out = []
    # arithmetic equalities (true + off-by-delta false)
    for _ in range(420):
        a, b = random.randint(2, 99), random.randint(2, 40)
        op, sym = random.choice([("+", "+"), ("-", "-"), ("*", "*")])
        correct = {"+": a + b, "-": a - b, "*": a * b}[op]
        truth = random.random() < 0.5
        val = correct if truth else correct + random.choice([-3, -2, -1, 1, 2, 3])
        out.append((f"Verify the claim: {a} {sym} {b} = {val}", eq(f"{a}{op}{b}", str(val))))
    # powers
    for _ in range(180):
        a, n = random.randint(2, 12), random.randint(2, 6)
        correct = a ** n
        truth = random.random() < 0.5
        val = correct if truth else correct + random.choice([-2, -1, 1, 2])
        out.append((f"Verify the claim: {a}^{n} = {val}", eq(f"{a}**{n}", str(val))))
    # derivatives of monomials  d/dx (c*x^n) = c*n*x^(n-1)
    for _ in range(260):
        c, n = random.randint(1, 9), random.randint(2, 7)
        truth = random.random() < 0.5
        good = f"{c*n}*x**{n-1}"
        bad = f"{c*n + random.choice([-1,1,2])}*x**{n-1}"
        claimed = good if truth else bad
        out.append((f"Verify: d/dx of {c}*x^{n} = {claimed}", dv(f"{c}*x**{n}", "x", claimed)))
    # inequalities
    for _ in range(160):
        a, b = random.randint(1, 99), random.randint(1, 99)
        op = random.choice(["<", ">", "<=", ">="])
        out.append((f"Verify the inequality: {a} {op} {b}", iq(str(a), str(b), op)))
    random.shuffle(out)
    return out


def to_pair(prompt, spec):
    r = D.verify_derivation([{"id": "s", "domain": "mathematics", "spec": spec}])
    verdict = r.get("verdict", "ERROR")
    trail = r.get("trail") or []
    if not trail or verdict == "ERROR":
        return None
    lines = [f"  [{s.get('status')}] {s.get('detail','')}" for s in trail]
    if verdict == "HOLDS":
        close = ("Confirmed by computation, not assertion — the trail above is the receipt, "
                 "not a 'trust me.'")
    else:
        close = ("The engine eliminates what is not the answer; the first step that fails is "
                 "shown above. A claim is not accepted because it sounds right — only because "
                 "it survives the check.")
    completion = (f"Verdict: {verdict}.\n"
                  f"Trail (the trail is the trust — every step checked deterministically):\n"
                  + "\n".join(lines) + f"\n{close}")
    return {
        "schema": "narrowhighway.training_pair/1",
        "source_kind": "method",
        "source_schema": "narrowhighway.derivation_verify/1",
        "source_slug": "",
        "created_at": "",
        "prompt": prompt,
        "completion": completion,
        "metadata": {"domain": "mathematics", "mode": spec["mode"], "verdict": verdict},
    }


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    out_path = OUT_DIR / f"corpus-method-{stamp}.jsonl"
    holds = broken = other = 0
    n = 0
    with out_path.open("w", encoding="utf-8") as fh:
        for prompt, spec in cases():
            p = to_pair(prompt, spec)
            if not p:
                continue
            v = p["metadata"]["verdict"]
            if v == "HOLDS":
                holds += 1
            elif v == "BROKEN":
                broken += 1
            else:
                other += 1
            fh.write(json.dumps(p, ensure_ascii=False) + "\n")
            n += 1
    print(f"wrote {n} method pairs -> {out_path.name}")
    print(f"  HOLDS={holds}  BROKEN={broken}  other={other}  (balanced verdicts = teaches catching falsehood)")


if __name__ == "__main__":
    main()
